replicaCount: 1

image:
  repository: mishazyat123/misha-test
  pullPolicy: IfNotPresent
  tag: "1.0"

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: hello-misha.yourdomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific

