replicaCount: 1

image:
  repository: mishazyat123/misha-test
  pullPolicy: IfNotPresent
  tag: "1.0"

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - host: hello-misha.best.domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:                   # Удаляем или комментируем TLS-блок, если не нужен HTTPS
    - hosts:
        - hello-misha.best.domain.com
#      secretName: hello-misha-tls
